(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Corr={
{1,0,0,0,0,0,0,0,rho1,0,0,0,0,0,0,0},
{0,1,0,0,0,0,0,0,0,rho2,0,0,0,0,0,0},
{0,0,1,0,0,0,0,0,0,0,rho3,0,0,0,0,0},
{0,0,0,1,0,0,0,0,0,0,0,rho4,0,0,0,0},
{0,0,0,0,1,0,0,0,0,0,0,0,rho5,0,0,0},
{0,0,0,0,0,1,0,0,0,0,0,0,0,rho6,0,0},
{0,0,0,0,0,0,1,0,0,0,0,0,0,0,rho7,0},
{0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,rho8},
{rho1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0},
{0,rho2,0,0,0,0,0,0,0,1,0,0,0,0,0,0},
{0,0,rho3,0,0,0,0,0,0,0,1,0,0,0,0,0},
{0,0,0,rho4,0,0,0,0,0,0,0,1,0,0,0,0},
{0,0,0,0,rho5,0,0,0,0,0,0,0,1,0,0,0},
{0,0,0,0,0,rho6,0,0,0,0,0,0,0,1,0,0},
{0,0,0,0,0,0,rho7,0,0,0,0,0,0,0,1,0},
{0,0,0,0,0,0,0,rho8,0,0,0,0,0,0,0,1}
};


Diff[x_]:=
D[x,S1]{alpha11 Sqrt[V1]S1,alpha12 Sqrt[V2]S1,alpha13 Sqrt[V3]S1,alpha14 Sqrt[V4]S1,Sqrt[V5] S1,0,0,0,0,0,0,0,0,0,0,0}+
D[x,S2]{alpha21 Sqrt[V1]S2,alpha22 Sqrt[V2]S2,alpha23 Sqrt[V3]S2,alpha24 Sqrt[V4]S2,0,Sqrt[V6] S2,0,0,0,0,0,0,0,0,0,0}+
D[x,S3]{alpha31 Sqrt[V1]S3,alpha32 Sqrt[V2]S3,alpha33 Sqrt[V3]S3,alpha34 Sqrt[V4]S3,0,0,Sqrt[V7] S3,0,0,0,0,0,0,0,0,0}+
D[x,S4]{alpha41 Sqrt[V1]S4,alpha42 Sqrt[V2]S4,alpha43 Sqrt[V3]S4,alpha44 Sqrt[V4]S4,0,0,0,Sqrt[V8] S4,0,0,0,0,0,0,0,0}+

D[x,V1]{0,0,0,0,0,0,0,0,kappaV1 Sqrt[V1],0,0,0,0,0,0,0}+
D[x,V2]{0,0,0,0,0,0,0,0,0,kappaV2 Sqrt[V2],0,0,0,0,0,0}+
D[x,V3]{0,0,0,0,0,0,0,0,0,0,kappaV3 Sqrt[V3],0,0,0,0,0}+
D[x,V4]{0,0,0,0,0,0,0,0,0,0,0,kappaV4 Sqrt[V4],0,0,0,0}+
D[x,V5]{0,0,0,0,0,0,0,0,0,0,0,0,kappaV5 Sqrt[V5],0,0,0}+
D[x,V6]{0,0,0,0,0,0,0,0,0,0,0,0,0,kappaV6 Sqrt[V6],0,0}+
D[x,V7]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,kappaV7 Sqrt[V7],0}+
D[x,V8]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,kappaV8 Sqrt[V8]}


zeroRule={kappaV1->0,kappaV2->0,kappaV3->0,kappaV4->0,kappaV5->0,kappaV6->0,kappaV7->0,kappaV8->0};


CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[spread_]:=
Module[{VS,VarVS,VarVS0,CoVarVS,CoVarVS0},
VS=Simplify[Diff[spread].(Corr.Diff[spread])];
VarVS=Simplify[Diff[VS].(Corr.Diff[VS])];
VarVS0=VarVS/.zeroRule;
CoVarVS=Simplify[Diff[VS].(Corr.Diff[spread])];
CoVarVS0=CoVarVS /.zeroRule;
Apply[Function,{{S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
rho1,kappaV1,V1,
rho2,kappaV2,V2,
rho3,kappaV3,V3,
rho4,kappaV4,V4,
rho5,kappaV5,V5,
rho6,kappaV6,V6,
rho7,kappaV7,V7,
rho8,kappaV8,V8},
{VS,Simplify[VarVS-VarVS0],Simplify[CoVarVS-CoVarVS0],Simplify[VarVS0],Simplify[CoVarVS0]}}]];


CompuputePureFunctionQuadriAlphaUnderlyingObservable[Under_]:=
Module[{VS,VarVS,CoVarVS},
VS=Simplify[Diff[Under].(Corr.Diff[Under])]/Under^2;
VarVS=Simplify[Diff[VS].(Corr.Diff[VS])];
CoVarVS=Simplify[Diff[VS].(Corr.Diff[Under])]/Under;
Apply[Function,{{S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
rho1,kappaV1,V1,
rho2,kappaV2,V2,
rho3,kappaV3,V3,
rho4,kappaV4,V4,
rho5,kappaV5,V5,
rho6,kappaV6,V6,
rho7,kappaV7,V7,
rho8,kappaV8,V8},
{VS,Simplify[VarVS],Simplify[CoVarVS]}}]];


QuadriBiSuperHestonUnderlyingObservable1z=CompuputePureFunctionQuadriAlphaUnderlyingObservable[S1];


VSUnderlying1z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable1z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSUnderlying1z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable1z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSUnderlying1z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable1z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


QuadriBiSuperHestonUnderlyingObservable2z=CompuputePureFunctionQuadriAlphaUnderlyingObservable[S2];


VSUnderlying2z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable2z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSUnderlying2z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable2z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSUnderlying2z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable2z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


QuadriBiSuperHestonUnderlyingObservable3z=CompuputePureFunctionQuadriAlphaUnderlyingObservable[S3];


VSUnderlying3z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable3z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSUnderlying3z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable3z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSUnderlying3z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable3z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


QuadriBiSuperHestonUnderlyingObservable4z=CompuputePureFunctionQuadriAlphaUnderlyingObservable[S4];


VSUnderlying4z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable4z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSUnderlying4z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable4z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSUnderlying4z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonUnderlyingObservable4z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


QuadriBiSuperHestonSpreadObservable12z=CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[(S2-S1)];


VSSpread12z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSSpread12z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSSpread12z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


VarVSSpread12z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]+QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[4]]


CoVarVSSpread12z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]+QuadriBiSuperHestonSpreadObservable12z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[5]]


QuadriBiSuperHestonSpreadObservable13z=CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[(S3-S1)];


VSSpread13z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSSpread13z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSSpread13z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


VarVSSpread13z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]+QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[4]]


CoVarVSSpread13z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]+QuadriBiSuperHestonSpreadObservable13z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[5]]


QuadriBiSuperHestonSpreadObservable14z=CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[(S4-S1)];


VSSpread14z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable14z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSSpread14z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable14z[S1,S2,S4,S3,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSSpread14z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable14z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


VarVSSpread14z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable14z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]+QuadriBiSuperHestonSpreadObservable14z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[4]]


CoVarVSSpread14z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable14z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]+QuadriBiSuperHestonSpreadObservable14z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[5]]


QuadriBiSuperHestonSpreadObservable23z=CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[(S3-S2)];


VSSpread23z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSSpread23z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSSpread23z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


VarVSSpread23z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]+QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[4]]


CoVarVSSpread23z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]+QuadriBiSuperHestonSpreadObservable23z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[5]]


QuadriBiSuperHestonSpreadObservable24z=CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[(S4-S2)];


VSSpread24z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSSpread24z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSSpread24z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


VarVSSpread24z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]+QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[4]]


CoVarVSSpread24z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]+QuadriBiSuperHestonSpreadObservable24z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[5]]


QuadriBiSuperHestonSpreadObservable34z=CompuputePureFunctionQuadriBiSuperHestonSpreadObservable[(S4-S3)];


VSSpread34z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[1]]


VarVSSpread34z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]


CoVarVSSpread34z[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]


VarVSSpread34z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[2]]+QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[4]]


CoVarVSSpread34z0[\[Rho]1_,\[Nu]1_,V01_,\[Rho]2_,\[Nu]2_,V02_,\[Rho]3_,\[Nu]3_,V03_,\[Rho]4_,\[Nu]4_,V04_,\[Rho]5_,\[Nu]5_,V05_,\[Rho]6_,\[Nu]6_,V06_,\[Rho]7_,\[Nu]7_,V07_,\[Rho]8_,\[Nu]8_,V08_]:=QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[3]]+QuadriBiSuperHestonSpreadObservable34z[S1,S2,S3,S4,
alpha11,alpha12,alpha13,alpha14,
alpha21,alpha22,alpha23,alpha24,
alpha31,alpha32,alpha33,alpha34,
alpha41,alpha42,alpha43,alpha44,
\[Rho]1,\[Nu]1,V01,
\[Rho]2,\[Nu]2,V02,
\[Rho]3,\[Nu]3,V03,
\[Rho]4,\[Nu]4,V04,
\[Rho]5,\[Nu]5,V05,
\[Rho]6,\[Nu]6,V06,
\[Rho]7,\[Nu]7,V07,
\[Rho]8,\[Nu]8,V08][[5]]


V0Bilog[VS1_,VS2_,VS12_,V12Iniz_,V12DerVS1z_,V12DerVS2z_,V12DerV12z_]:=V12Iniz+V12DerVS1z VS1+V12DerVS2z VS2+V12DerV12z VS12


V0Bilog[VS1_,VS2_,VS12_,V12Iniz_,V12DerVS1z_,V12DerVS2z_,V12DerV12z_]:=V12Iniz+V12DerVS1z VS1+V12DerVS2z VS2+V12DerV12z VS12


V12Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
V12Ini,V12DerV1,V12DerV2,V12DerV12]



V13Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
V13Ini,V13DerV1,V13DerV2,V13DerV12]



V14Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
V14Ini,V14DerV1,V14DerV2,V14DerV12]



V23Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
V23Ini,V23DerV1,V23DerV2,V23DerV12]



V24Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
V24Ini,V24DerV1,V24DerV2,V24DerV12]



V34Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
V34Ini,V34DerV1,V34DerV2,V34DerV12]



CovV12Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
CovV12Ini,CovV12DerV1,CovV12DerV2,CovV12DerV12]



CovV13Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
CovV13Ini,CovV13DerV1,CovV13DerV2,CovV13DerV12]



CovV14Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
CovV14Ini,CovV14DerV1,CovV14DerV2,CovV14DerV12]



CovV23Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
CovV23Ini,CovV23DerV1,CovV23DerV2,CovV23DerV12]



CovV24Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
CovV24Ini,CovV24DerV1,CovV24DerV2,CovV24DerV12]



CovV34Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
CovV34Ini,CovV34DerV1,CovV34DerV2,CovV34DerV12]



VarV12Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VarV12Ini,VarV12DerV1,VarV12DerV2,VarV12DerV12]



VarV13Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VarV13Ini,VarV13DerV1,VarV13DerV2,VarV13DerV12]



VarV14Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VarV14Ini,VarV14DerV1,VarV14DerV2,VarV14DerV12]



VarV23Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VarV23Ini,VarV23DerV1,VarV23DerV2,VarV23DerV12]



VarV24Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VarV24Ini,VarV24DerV1,VarV24DerV2,VarV24DerV12]



VarV34Bilog[rho1_, kappaV1_, V1_, rho2_, kappaV2_, V2_, rho3_, kappaV3_, V3_, rho4_, kappaV4_, V4_,
      rho5_, kappaV5_, V5_, rho6_, kappaV6_, V6_,  rho7_, kappaV7_, V7_, rho8_, kappaV8_, V8_]:=V0Bilog[
VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8],
VarV34Ini,VarV34DerV1,VarV34DerV2,VarV34DerV12]



Objz=CoeffVU1 (VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU1)^2+
CoeffVU2 (VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU2)^2+
CoeffVU3 (VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU3)^2+
CoeffVU4 (VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU4)^2+
CoeffVarVU1 (VarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1^2 VU1)^2+
CoeffVarVU2 (VarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2^2 VU2)^2+
CoeffVarVU3 (VarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3^2 VU3)^2+
CoeffVarVU4 (VarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4^2 VU4)^2+
CoeffCovVU1 (CoVarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1 rhoU1 VU1)^2+
CoeffCovVU2 (CoVarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2 rhoU2 VU2)^2+
CoeffCovVU3 (CoVarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3 rhoU3 VU3)^2+
CoeffCovVU4 (CoVarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4 rhoU4 VU4)^2+
CoeffVSpread12 (VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V12+V12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVSpread13 (VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V13+V13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVSpread14 (VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V14+V14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVSpread23 (VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V23+V23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVSpread24 (VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V24+V24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVSpread34 (VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V34+V34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffCovSpread12 (CoVarVSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread12+CovV12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVarSpread12 (VarVSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread12+VarV12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffCovSpread13 (CoVarVSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread13+CovV13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVarSpread13 (VarVSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread13+VarV13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffCovSpread14 (CoVarVSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread14+CovV14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVarSpread14 (VarVSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread14+VarV14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffCovSpread23 (CoVarVSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread23+CovV23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVarSpread23 (VarVSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread23+VarV23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffCovSpread24 (CoVarVSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread24+CovV24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVarSpread24 (VarVSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread24+VarV24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffCovSpread34 (CoVarVSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread34+CovV34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2+
CoeffVarSpread34 (VarVSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread34+VarV34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])^2;


Objz0=CoeffVU1 (VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU1)^2+
CoeffVU2 (VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU2)^2+
CoeffVU3 (VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU3)^2+
CoeffVU4 (VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU4)^2+
CoeffVarVU1 (VarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1^2 VU1)^2+
CoeffVarVU2 (VarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2^2 VU2)^2+
CoeffVarVU3 (VarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3^2 VU3)^2+
CoeffVarVU4 (VarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4^2 VU4)^2+
CoeffCovVU1 (CoVarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1 rhoU1 VU1)^2+
CoeffCovVU2 (CoVarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2 rhoU2 VU2)^2+
CoeffCovVU3 (CoVarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3 rhoU3 VU3)^2+
CoeffCovVU4 (CoVarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4 rhoU4 VU4)^2+
CoeffVSpread12 (VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V12)^2+
CoeffVSpread13 (VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V13)^2+
CoeffVSpread14 (VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V14)^2+
CoeffVSpread23 (VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V23)^2+
CoeffVSpread24 (VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V24)^2+
CoeffVSpread34 (VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V34)^2+
CoeffCovSpread12 (CoVarVSSpread12z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread12)^2+
CoeffVarSpread12 (VarVSSpread12z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread12)^2+
CoeffCovSpread13 (CoVarVSSpread13z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread13)^2+
CoeffVarSpread13 (VarVSSpread13z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread13)^2+
CoeffCovSpread14 (CoVarVSSpread14z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread14)^2+
CoeffVarSpread14 (VarVSSpread14z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread14)^2+
CoeffCovSpread23 (CoVarVSSpread23z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread23)^2+
CoeffVarSpread23 (VarVSSpread23z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread23)^2+
CoeffCovSpread24 (CoVarVSSpread24z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread24)^2+
CoeffVarSpread24 (VarVSSpread24z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread24)^2+
CoeffCovSpread34 (CoVarVSSpread34z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread34)^2+
CoeffVarSpread34 (VarVSSpread34z0[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread34)^2;





ObjzVector={(VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU1),
(VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU2),
(VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU3),
(VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU4),
(VarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1^2 VU1),
(VarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2^2 VU2),
(VarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3^2 VU3),
(VarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4^2 VU4),
(CoVarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1 rhoU1 VU1),
(CoVarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2 rhoU2 VU2),
(CoVarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3 rhoU3 VU3),
(CoVarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4 rhoU4 VU4),
(VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V12+V12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V13+V13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V14+V14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V23+V23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V24+V24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V34+V34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread12+CovV12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread12+VarV12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread13+CovV13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread13+VarV13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread14+CovV14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread14+VarV14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread23+CovV23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread23+VarV23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread24+CovV24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread24+VarV24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread34+CovV34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread34+VarV34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])};


DimensionSwitch[j_]:=Switch[j,1,rho1,
2,rho2,
3,rho3,
4,rho4,
5,rho5,
6,rho6,
7,rho7,
8,rho8,
9,kappaV1,
10,kappaV2,
11,kappaV3,
12,kappaV4,
13,kappaV5,
14,kappaV6,
15,kappaV7,
16,kappaV8,
17,V1,
18,V2,
19,V3,
20,V4,
21,V5,
22,V6,
23,V7,
24,V8,
25,alpha11,
26,alpha12,
27,alpha13,
28,alpha14,
29,alpha21,
30,alpha22,
31,alpha23,
32,alpha24,
33,alpha31,
34,alpha32,
35,alpha33,
36,alpha34,
37,alpha41,
38,alpha42,
39,alpha43,
40,alpha44]


CoefficientSwitch[j_]:=Switch[j,1,CoeffVU1,
2,CoeffVU2,
3,CoeffVU3,
4,CoeffVU4,
5,CoeffVarVU1,
6,CoeffVarVU2,
7,CoeffVarVU3,
8,CoeffVarVU4,
9,CoeffCovVU1,
10,CoeffCovVU2,
11,CoeffCovVU3,
12,CoeffCovVU4,
13,CoeffVSpread12,
14,CoeffVSpread13,
15,CoeffVSpread14,
16,CoeffVSpread23,
17,CoeffVSpread24,
18,CoeffVSpread34,
19,CoeffCovSpread12,
20,CoeffVarSpread12,
21,CoeffCovSpread13,
22,CoeffVarSpread13,
23,CoeffCovSpread14,
24,CoeffVarSpread14,
25,CoeffCovSpread23,
26,CoeffVarSpread23,
27,CoeffCovSpread24,
28,CoeffVarSpread24,
29,CoeffCovSpread34,
30,CoeffVarSpread34]


ObjzVector={(VSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU1),
(VSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU2),
(VSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU3),
(VSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VU4),
(VarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1^2 VU1),
(VarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2^2 VU2),
(VarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3^2 VU3),
(VarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4^2 VU4),
(CoVarVSUnderlying1z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU1 rhoU1 VU1),
(CoVarVSUnderlying2z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU2 rhoU2 VU2),
(CoVarVSUnderlying3z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU3 rhoU3 VU3),
(CoVarVSUnderlying4z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-kappaU4 rhoU4 VU4),
(VSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V12+V12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V13+V13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V14+V14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V23+V23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V24+V24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-V34+V34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread12+CovV12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread12z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread12+VarV12Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread13+CovV13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread13z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread13+VarV13Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread14+CovV14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread14z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread14+VarV14Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread23+CovV23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread23z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -VarSpread23+VarV23Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] - CovSpread24+CovV24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread24z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread24+VarV24Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(CoVarVSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8] -CovSpread34+CovV34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8]),
(VarVSSpread34z[rho1, kappaV1, V1, rho2,kappaV2, V2, rho3,kappaV3, V3,rho4, kappaV4, V4,
  rho5, kappaV5, V5, rho6, kappaV6, V6,  rho7, kappaV7, V7, rho8,kappaV8, V8]-VarSpread34+VarV34Bilog[rho1,kappaV1,V1,rho2,kappaV2,V2,rho3,kappaV3,V3,rho4,kappaV4,V4,rho5,kappaV5,V5,rho6,kappaV6,V6,rho7,kappaV7,V7,rho8,kappaV8,V8])};


DimensionSwitch[j_]:=Switch[j,1,rho1,
2,rho2,
3,rho3,
4,rho4,
5,rho5,
6,rho6,
7,rho7,
8,rho8,
9,kappaV1,
10,kappaV2,
11,kappaV3,
12,kappaV4,
13,kappaV5,
14,kappaV6,
15,kappaV7,
16,kappaV8,
17,V1,
18,V2,
19,V3,
20,V4,
21,V5,
22,V6,
23,V7,
24,V8,
25,alpha11,
26,alpha12,
27,alpha13,
28,alpha14,
29,alpha21,
30,alpha22,
31,alpha23,
32,alpha24,
33,alpha31,
34,alpha32,
35,alpha33,
36,alpha34,
37,alpha41,
38,alpha42,
39,alpha43,
40,alpha44]


CoefficientSwitch[j_]:=Switch[j,1,CoeffVU1,
2,CoeffVU2,
3,CoeffVU3,
4,CoeffVU4,
5,CoeffVarVU1,
6,CoeffVarVU2,
7,CoeffVarVU3,
8,CoeffVarVU4,
9,CoeffCovVU1,
10,CoeffCovVU2,
11,CoeffCovVU3,
12,CoeffCovVU4,
13,CoeffVSpread12,
14,CoeffVSpread13,
15,CoeffVSpread14,
16,CoeffVSpread23,
17,CoeffVSpread24,
18,CoeffVSpread34,
19,CoeffCovSpread12,
20,CoeffVarSpread12,
21,CoeffCovSpread13,
22,CoeffVarSpread13,
23,CoeffCovSpread14,
24,CoeffVarSpread14,
25,CoeffCovSpread23,
26,CoeffVarSpread23,
27,CoeffCovSpread24,
28,CoeffVarSpread24,
29,CoeffCovSpread34,
30,CoeffVarSpread34]



